version: '3'
services:
  server-api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    links:
      - mongo
      - redis
    environment:
      MONGO_CONNECTION_STRING: mongodb://mongo:27017/Notifications
      API_KEY: Xy8NsXxfJg2cQ2YQ4pax6aLrTcj55jZ9mbsNCM30 
      REDIS_URL: redis://redis
      APP_EMAIL: gaykinrele002@gmail.com
      APP_EMAIL_PASS: yejtzcienrovrfdg

  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./mongo/data:/data/db
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis_data:/data
    restart: always
    expose:
      - "6379"
